/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mars.rover;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {

    @Test
    public void testRotateRoverLeft() {
        {
            Library.Rover r = new Library.Rover(1, 2, Library.Orientation.N);
            assertEquals(r.rotateLeft(), new Library.Rover(1, 2, Library.Orientation.W));
        }

        {
            Library.Rover r = new Library.Rover(1, 2, Library.Orientation.W);
            assertEquals(r.rotateLeft(), new Library.Rover(1, 2, Library.Orientation.S));
        }
        {
            Library.Rover r = new Library.Rover(1, 2, Library.Orientation.S);
            assertEquals(r.rotateLeft(), new Library.Rover(1, 2, Library.Orientation.E));
        }
        {
            Library.Rover r = new Library.Rover(1, 2, Library.Orientation.E);
            assertEquals(r.rotateLeft(), new Library.Rover(1, 2, Library.Orientation.N));
        }
    }
    @Test
    public void testRotateRoverRight() {
        {
            Library.Rover r = new Library.Rover(1, 2, Library.Orientation.N);
            assertEquals(r.rotateRight(), new Library.Rover(1, 2, Library.Orientation.E));
        }

        {
            Library.Rover r = new Library.Rover(1, 2, Library.Orientation.W);
            assertEquals(r.rotateRight(), new Library.Rover(1, 2, Library.Orientation.N));
        }
        {
            Library.Rover r = new Library.Rover(1, 2, Library.Orientation.S);
            assertEquals(r.rotateRight(), new Library.Rover(1, 2, Library.Orientation.W));
        }
        {
            Library.Rover r = new Library.Rover(1, 2, Library.Orientation.E);
            assertEquals(r.rotateRight(), new Library.Rover(1, 2, Library.Orientation.S));
        }
    }

    @Test
    public void testExecInstruction() {
        {
            Library.Rover r = new Library.Rover(1, 2, Library.Orientation.N);
            assertEquals(r.exec(Library.Instruction.Move), new Library.Rover(1, 3, Library.Orientation.N));
        }

        {
            Library.Rover r = new Library.Rover(1, 2, Library.Orientation.S);
            assertEquals(r.exec(Library.Instruction.Move), new Library.Rover(1, 1, Library.Orientation.S));
        }

    }

    @Test
    public void testEquals() {
        Library.Rover r = new Library.Rover(1, 2, Library.Orientation.N);
        Library.Rover r2 = new Library.Rover(1, 2, Library.Orientation.N);

        assertEquals(r, r2);
    }
}
