/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mars.rover;

import org.junit.Test;

import mars.rover.Library;
import mars.rover.Library.*;

import static org.junit.Assert.*;

public class ParserTest {

    @Test
    public void testParseRover() {
        {
            Library.Rover r = Parser.parseRover("1 2 N");
            assertEquals(r, new Library.Rover(1, 2, Library.Orientation.N));
        }
        {
            Library.Rover r = Parser.parseRover("2 2 S");
            assertEquals(r, new Library.Rover(2, 2, Library.Orientation.S));
        }
    }

    @Test
    public void testParseInstruction() {
        assertEquals(Library.Instruction.Move, Parser.parseInstruction("M"));
        assertEquals(Library.Instruction.Left, Parser.parseInstruction("L"));
        assertEquals(Library.Instruction.Right, Parser.parseInstruction("R"));
    }

    @Test
    public void testParseInstructions() {
        {
            Instruction[] expected = new Instruction[]{Instruction.Move, Instruction.Left, Instruction.Right};
            assertEquals(Parser.parseInstructions("MLR"), expected);
        }

        {
            Instruction[] expected = new Instruction[]{Instruction.Right, Instruction.Right, Instruction.Right};
            assertEquals(Parser.parseInstructions("RRR"), expected);
        }
    }

    @Test
    public void testRunProgram() {
        {
            String program = "5 5\n1 2 N\nLMLMLMLMM";
            Rover expected = new Library.Rover(1, 3, Library.Orientation.N);

            assertEquals(Parser.runProgram(program), new Library.Rover[]{expected});
        }
        {
            String program = "5 5\n1 2 N\nLMLMLMLMMM";
            Rover expected = new Library.Rover(1, 4, Library.Orientation.N);

            assertEquals(Parser.runProgram(program), new Library.Rover[]{expected});
        }


        {
            String program = "5 5\n1 2 N\nLMLMLMLMMM\n1 2 N\nLMLMLMLMM";
            Rover expected1 = new Library.Rover(1, 4, Library.Orientation.N);
            Rover expected2 = new Library.Rover(1, 3, Library.Orientation.N);

            assertEquals(Parser.runProgram(program), new Library.Rover[]{
                expected1,
                expected2
            });
        }
    }
}
