/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mars.rover;

import org.junit.Test;

import mars.rover.Rover;
import mars.rover.Rover.*;
import static org.junit.Assert.*;

public class ParserTest {

    @Test
    public void testParseRover() {
        {
            Rover r = Parser.parseRover("1 2 N");
            assertEquals(r, new Rover(1, 2, Rover.Orientation.N));
        }
        {
            Rover r = Parser.parseRover("2 2 S");
            assertEquals(r, new Rover(2, 2, Rover.Orientation.S));
        }
    }

    @Test
    public void testParseInstruction() {
        assertEquals(Rover.Instruction.Move, Parser.parseInstruction("M"));
        assertEquals(Rover.Instruction.Left, Parser.parseInstruction("L"));
        assertEquals(Rover.Instruction.Right, Parser.parseInstruction("R"));
    }

    @Test
    public void testParseInstructions() {
        {
            Instruction[] expected = new Instruction[]{Instruction.Move, Instruction.Left, Instruction.Right};
            assertEquals(Parser.parseInstructions("MLR"), expected);
        }

        {
            Instruction[] expected = new Instruction[]{Instruction.Right, Instruction.Right, Instruction.Right};
            assertEquals(Parser.parseInstructions("RRR"), expected);
        }
    }

    @Test
    public void testRunProgram() {
        {
            String program = "5 5\n1 2 N\nLMLMLMLMM";
            Rover expected = new Rover(1, 3, Rover.Orientation.N);

            assertEquals(Parser.runProgram(program), new Rover[]{expected});
        }
        {
            String program = "5 5\n1 2 N\nLMLMLMLMMM";
            Rover expected = new Rover(1, 4, Rover.Orientation.N);

            assertEquals(Parser.runProgram(program), new Rover[]{expected});
        }


        {
            String program = "5 5\n1 2 N\nLMLMLMLMMM\n1 2 N\nLMLMLMLMM";
            Rover expected1 = new Rover(1, 4, Rover.Orientation.N);
            Rover expected2 = new Rover(1, 3, Rover.Orientation.N);

            assertEquals(Parser.runProgram(program), new Rover[]{
                expected1,
                expected2
            });
        }
    }
}
