/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mars.rover;

import org.junit.Test;

import java.util.ArrayList;
import mars.rover.Rover;
import mars.rover.Rover.*;
import static org.junit.Assert.*;

public class ParserTest {

    @Test
    public void testParseRover() {
        {
            Rover r = Parser.parseRover("1 2 N");
            assertEquals(r, new Rover(1, 2, Rover.Orientation.N));
        }
        {
            Rover r = Parser.parseRover("2 2 S");
            assertEquals(r, new Rover(2, 2, Rover.Orientation.S));
        }
    }

    @Test
    public void testParseInstruction() {
        assertEquals(Rover.Instruction.Move, Parser.parseInstruction("M"));
        assertEquals(Rover.Instruction.Left, Parser.parseInstruction("L"));
        assertEquals(Rover.Instruction.Right, Parser.parseInstruction("R"));
    }

    @Test
    public void testParseInstructions() {
        {
            ArrayList<Instruction> expected = new ArrayList<Instruction>() {
                {
                    add(Instruction.Move);
                    add(Instruction.Left);
                    add(Instruction.Right);
                }
            };
            assertEquals(Parser.parseInstructions("MLR"), expected);
        }

        {

            ArrayList<Instruction> expected = new ArrayList<Instruction>() {
                {
                    add(Instruction.Right);
                    add(Instruction.Right);
                    add(Instruction.Right);
                }
            };
            assertEquals(Parser.parseInstructions("RRR"), expected);
        }
    }

    @Test
    public void testRunProgram1() {
        String program = "5 5\n1 2 N\nLMLMLMLMM";
        Rover expected = new Rover(1, 3, Rover.Orientation.N);
        System.out.println(Parser.runProgram(program));

        assertEquals(Parser.runProgram(program), new Rover[] { expected });
    }

    @Test
    public void testRunProgram2() {
        String program = "5 5\n1 2 N\nLMLMLMLMMM";
        Rover expected = new Rover(1, 4, Rover.Orientation.N);
        System.out.println(Parser.runProgram(program));

        assertEquals(Parser.runProgram(program), new Rover[] { expected });
    }

    @Test
    public void testRunProgram3() {
        String program = "5 5\n1 2 N\nLMLMLMLMMM\n1 2 N\nLMLMLMLMM";
        Rover expected1 = new Rover(1, 4, Rover.Orientation.N);
        Rover expected2 = new Rover(1, 3, Rover.Orientation.N);

        System.out.println(Parser.runProgram(program));
        assertEquals(Parser.runProgram(program), new Rover[] { expected1, expected2 });
    }
}
